title: ARM Tutorials
author: ARM Development Team
logo: images/arm_logo.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - html_image
repository:
  url: "https://github.com/ARM-Development/ARM-Notebooks"  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
  path_to_book: ../user-data-home/ARM-Notebooks
launch_buttons:
  jupyterhub_url: "https://jupyterhub.arm.gov"
  notebook_interface: "jupyterlab"
