title: ARM Tutorials
author: ARM Development Team
logo: images/arm_logo.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - html_image
repository:
  url: https%3A%2F%2Fgithub.com%2FARM-Development%2FARM-Notebook  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  jupyterhub_url: "https://jupyterhub.arm.gov"
  notebook_interface: "jupyterlab"
