name: arm-tutorial-dev
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - xarray
  - matplotlib
  - dask
  - distributed
  - arm_pyart
  - act-atmos
  - metpy=1.3
  - siphon=0.9
  - cartopy
  - emc2
  - cmweather
  - pip
  - pip:
      - jupyter-book
      - git+https://github.com/eagles-project/ESMAC_diags
