name: esmac_diags
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - matplotlib
  - numpy
  - scipy
  - sphinx
  - conda-build
  - pytest
  - pytest-shutil
  - ipython
  - black
  - netCDF4
  - xarray
  - pandas
  - dask
