name: arm-tutorial-dev
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - xarray
  - matplotlib
  - dask
  - distributed
  - arm_pyart
  - act-atmos
  - metpy
  - cartopy
  - emc2
  - pip
  - pip:
      - jupyter-book
